//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCompanion.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudyCompanion.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gluten.
        /// </summary>
        internal static string A1 {
            get {
                return ResourceManager.GetString("A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mustard and products/foods containing mustard.
        /// </summary>
        internal static string A10 {
            get {
                return ResourceManager.GetString("A10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesame and products/foods containing sesame.
        /// </summary>
        internal static string A11 {
            get {
                return ResourceManager.GetString("A11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulfur und sulfite.
        /// </summary>
        internal static string A12 {
            get {
                return ResourceManager.GetString("A12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lupine and products/foods containing lupine.
        /// </summary>
        internal static string A13 {
            get {
                return ResourceManager.GetString("A13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mollusk and products/foods containing mollusk.
        /// </summary>
        internal static string A14 {
            get {
                return ResourceManager.GetString("A14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shellfish and products/foods containing shellfish.
        /// </summary>
        internal static string A2 {
            get {
                return ResourceManager.GetString("A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eggs and products/foods containing eggs.
        /// </summary>
        internal static string A3 {
            get {
                return ResourceManager.GetString("A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish.
        /// </summary>
        internal static string A4 {
            get {
                return ResourceManager.GetString("A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peanuts and products/foods containing peanuts.
        /// </summary>
        internal static string A5 {
            get {
                return ResourceManager.GetString("A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soy and products/foods containing soy.
        /// </summary>
        internal static string A6 {
            get {
                return ResourceManager.GetString("A6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milk and products/foods containing milk (including lactose).
        /// </summary>
        internal static string A7 {
            get {
                return ResourceManager.GetString("A7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuts and products/foods containing nuts.
        /// </summary>
        internal static string A8 {
            get {
                return ResourceManager.GetString("A8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celery and products/foods containing celery.
        /// </summary>
        internal static string A9 {
            get {
                return ResourceManager.GetString("A9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additives.
        /// </summary>
        internal static string Additives {
            get {
                return ResourceManager.GetString("Additives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergens.
        /// </summary>
        internal static string Allergens {
            get {
                return ResourceManager.GetString("Allergens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitencodings.
        /// </summary>
        internal static string Bitencodings {
            get {
                return ResourceManager.GetString("Bitencodings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buddy.
        /// </summary>
        internal static string Buddy {
            get {
                return ResourceManager.GetString("Buddy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export course to calendar?.
        /// </summary>
        internal static string CalendarExportQuery {
            get {
                return ResourceManager.GetString("CalendarExportQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        internal static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC.
        /// </summary>
        internal static string CRC {
            get {
                return ResourceManager.GetString("CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desserts.
        /// </summary>
        internal static string Desserts {
            get {
                return ResourceManager.GetString("Desserts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while fetching the data. Please try again later..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise Basic Layout.
        /// </summary>
        internal static string ExerciseBasicLayout {
            get {
                return ResourceManager.GetString("ExerciseBasicLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises.
        /// </summary>
        internal static string Exercises {
            get {
                return ResourceManager.GetString("Exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        internal static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRZ: 0 = -  |  1 = +
        ///            NRZI: 1 = Voltage change (+/-) 
        ///            MLT-3: 1 = alternating +, 0 and -.
        /// </summary>
        internal static string InfoText_BitEncoding {
            get {
                return ResourceManager.GetString("InfoText_BitEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process {0} is finished, memory is freed..
        /// </summary>
        internal static string InfoText_Buddy_Final {
            get {
                return ResourceManager.GetString("InfoText_Buddy_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process {0} requests {1} KB of memory. {2} KB are allocated for the process..
        /// </summary>
        internal static string InfoText_Buddy_Request {
            get {
                return ResourceManager.GetString("InfoText_Buddy_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remaining bit sequence is called the check bit and can be used for the check afterwards..
        /// </summary>
        internal static string InfoText_CRC_check {
            get {
                return ResourceManager.GetString("InfoText_CRC_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the bit sequence remaining at the end is 0, the transmission was successful..
        /// </summary>
        internal static string InfoText_CRC_check_Finish {
            get {
                return ResourceManager.GetString("InfoText_CRC_check_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The original bit sequence {0} is extended by the check bit {1}. An XOR division is then carried out with the fixed generator polynomial 100101..
        /// </summary>
        internal static string InfoText_CRC_check_Start {
            get {
                return ResourceManager.GetString("InfoText_CRC_check_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An XOR division with the generator polynomial 100101 is again carried out on the resulting bit sequence..
        /// </summary>
        internal static string InfoText_CRC_evenStep {
            get {
                return ResourceManager.GetString("InfoText_CRC_evenStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bit sequence {0} is extended by 5 zeros. An XOR division is then carried out with the generator polynomial 100101 (CRC5)..
        /// </summary>
        internal static string InfoText_CRC_Start {
            get {
                return ResourceManager.GetString("InfoText_CRC_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XOR division is performed:
        ///                    
        ///1 over 1 equals 0
        ///0 over 0 equals 0
        ///1 over 0 equals 1
        ///0 over 1 equals 1
        ///                    
        ///Leading zeros can be omitted. The resulting bit string is extended back to 6 characters by pulling down the existing bits (zeros) of the bit string..
        /// </summary>
        internal static string InfoText_CRC_unevenStep {
            get {
                return ResourceManager.GetString("InfoText_CRC_unevenStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element {0} was added in Slot {1},.
        /// </summary>
        internal static string InfoText_PageReplacement_Element_Added {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Element_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to because the Slot was empty..
        /// </summary>
        internal static string InfoText_PageReplacement_Element_Added_Empty {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Element_Added_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to because the element contained in the Slot is not used anymore..
        /// </summary>
        internal static string InfoText_PageReplacement_Element_Added_NotInUse {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Element_Added_NotInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element is already present in Slot {0}..
        /// </summary>
        internal static string InfoText_PageReplacement_Element_Exists {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Element_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to because the last use of the element contained in the Slot is the furthest ({0}) in the past..
        /// </summary>
        internal static string InfoText_PageReplacement_Fifo_Element_Added_Distance {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Fifo_Element_Added_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to because the last use of the element contained in the Slot is the furthest ({0}) in the past..
        /// </summary>
        internal static string InfoText_PageReplacement_LRU_Element_Added_Distance {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_LRU_Element_Added_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to because the use of the element contained in the Slot is the furthest ({0}) in the future..
        /// </summary>
        internal static string InfoText_PageReplacement_Optimal_Element_Added_NotInUse {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_Optimal_Element_Added_NotInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first Slot that is considered according to the pointer is Slot {0}. 
        ///
        ///Because the reference bit of this Slot was 1, the bit is first set to 0, after that the next slot is considered. 
        ///
        ///Slot {1} was the first Slot with a reference bit = 0, where the element could be added. 
        ///
        ///Now the pointer point at Slot {2}.
        /// </summary>
        internal static string InfoText_PageReplacement_SecondChanceClock_Element_Added_NotPointer {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_SecondChanceClock_Element_Added_NotPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first Slot that is considered according to the pointer is Slot {0}. \n\nBecause the reference bit of this Slot was 0, the element could be added. 
        ///
        ///Now the pointer point at Slot {1}..
        /// </summary>
        internal static string InfoText_PageReplacement_SecondChanceClock_Element_Added_Pointer {
            get {
                return ResourceManager.GetString("InfoText_PageReplacement_SecondChanceClock_Element_Added_Pointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process {0} currently has priority according EDF, because he has the earliest deadline. \n\nIt is started, since no other process with an earlier deadline is ready..
        /// </summary>
        internal static string InfoText_RealTimeScheduling_EDF {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_EDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///EDF = Earliest Deadline First 
        ///
        ///The priority of a process is derived depending on the deadline of the process. The earlier the deadline, the higher of a priority is given..
        /// </summary>
        internal static string InfoText_RealTimeScheduling_EDF_Info {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_EDF_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because the process {0} has the highest priority according to RMS, it is executed immedeately. 
        ///
        ///The process can interrupt other processes with low or medium priority..
        /// </summary>
        internal static string InfoText_RealTimeScheduling_RMS_High {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_RMS_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///RMS = Rate Monotonous Scheduling 
        ///
        ///The priority of a process is derived depending on how often a process appears. The more often a process appears, the higher of a priority is given..
        /// </summary>
        internal static string InfoText_RealTimeScheduling_RMS_Info {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_RMS_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process {0} has low priority according to RMS. 
        ///
        ///It is executed, since no other process with a higher priority is ready. 
        ///
        ///The process can be interrupted by other processes with medium or high priority..
        /// </summary>
        internal static string InfoText_RealTimeScheduling_RMS_Low {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_RMS_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process {0} has medium priority according to RMS. 
        ///
        ///It is executed, since no other process with a higher priority is ready. 
        ///
        ///The process can interrupt other processes with low priority and be interrupted by processes with high priority..
        /// </summary>
        internal static string InfoText_RealTimeScheduling_RMS_Medium {
            get {
                return ResourceManager.GetString("InfoText_RealTimeScheduling_RMS_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation.
        /// </summary>
        internal static string InfoText_Scheduling_Calculation {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string InfoText_Scheduling_Duration {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The processes are processed in order of appearance.
        ///
        ///For the total waiting time, the running time of each process is multiplied by the number of ready processes. The result is summed and divided by the number of processes..
        /// </summary>
        internal static string InfoText_Scheduling_FirstComeFirstServed_Info {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_FirstComeFirstServed_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string InfoText_Scheduling_Priority {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The processes are processed in order according to their priority.
        ///
        ///For the total waiting time, the runtime of each process is multiplied by the respective priority. The result is summed up and divided by the number of processes..
        /// </summary>
        internal static string InfoText_Scheduling_Priority_Info {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_Priority_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string InfoText_Scheduling_Result {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After {0} time unit:.
        /// </summary>
        internal static string InfoText_Scheduling_RoundRobin_AfterTimeUnit {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_RoundRobin_AfterTimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After {0} time units:.
        /// </summary>
        internal static string InfoText_Scheduling_RoundRobin_AfterTimeUnits {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_RoundRobin_AfterTimeUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin:.
        /// </summary>
        internal static string InfoText_Scheduling_RoundRobin_Begin {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_RoundRobin_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to According to the round robin method, each process in ready state is granted the same computing time. If a process is completed, the computing time each process gets is distributed again.
        ///
        ///The total wait time is the units of time it takes for each process to complete multiplied by the number of processes that are in ready state, divided by the total number of processes..
        /// </summary>
        internal static string InfoText_Scheduling_RoundRobin_Info {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_RoundRobin_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting time:.
        /// </summary>
        internal static string InfoText_Scheduling_RoundRobin_WaitingTime {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_RoundRobin_WaitingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The processes are processed one after another, while processes with a short runtime are prioritized.
        ///
        ///For the total waiting time, the running time of each process is multiplied by the number of processes in ready state. The sum of the result is divided by the number of processes..
        /// </summary>
        internal static string InfoText_Scheduling_ShortestJobFirst_Info {
            get {
                return ResourceManager.GetString("InfoText_Scheduling_ShortestJobFirst_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please allow calendar access in the Settings app..
        /// </summary>
        internal static string IOSPermissions {
            get {
                return ResourceManager.GetString("IOSPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dishes.
        /// </summary>
        internal static string Maindishes {
            get {
                return ResourceManager.GetString("Maindishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensa.
        /// </summary>
        internal static string Mensa {
            get {
                return ResourceManager.GetString("Mensa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients/Nutritional information is available at Studierendenwerk Paderborn&apos;s web page..
        /// </summary>
        internal static string MensaInfo {
            get {
                return ResourceManager.GetString("MensaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Spanning Tree.
        /// </summary>
        internal static string MST {
            get {
                return ResourceManager.GetString("MST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shortest path to connect .
        /// </summary>
        internal static string MSTV_Info_1 {
            get {
                return ResourceManager.GetString("MSTV_Info_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  with .
        /// </summary>
        internal static string MSTV_Info_2 {
            get {
                return ResourceManager.GetString("MSTV_Info_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is over the edge .
        /// </summary>
        internal static string MSTV_Info_3 {
            get {
                return ResourceManager.GetString("MSTV_Info_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with the tag .
        /// </summary>
        internal static string MSTV_Info_4 {
            get {
                return ResourceManager.GetString("MSTV_Info_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netmasks.
        /// </summary>
        internal static string Netmasks {
            get {
                return ResourceManager.GetString("Netmasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networks.
        /// </summary>
        internal static string Networks {
            get {
                return ResourceManager.GetString("Networks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Values.
        /// </summary>
        internal static string NewValues {
            get {
                return ResourceManager.GetString("NewValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No editable calendars..
        /// </summary>
        internal static string NoCalendars {
            get {
                return ResourceManager.GetString("NoCalendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No meals to display. Mensa closed?.
        /// </summary>
        internal static string NoMeals {
            get {
                return ResourceManager.GetString("NoMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating Systems.
        /// </summary>
        internal static string OperatingSystems {
            get {
                return ResourceManager.GetString("OperatingSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Replacement.
        /// </summary>
        internal static string PageReplacement {
            get {
                return ResourceManager.GetString("PageReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar access is needed for calendar export..
        /// </summary>
        internal static string PermissionRationale {
            get {
                return ResourceManager.GetString("PermissionRationale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students / Staff / Guests.
        /// </summary>
        internal static string PricesLabel {
            get {
                return ResourceManager.GetString("PricesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        internal static string Processes {
            get {
                return ResourceManager.GetString("Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profs.
        /// </summary>
        internal static string Profs {
            get {
                return ResourceManager.GetString("Profs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change the setting later!.
        /// </summary>
        internal static string QueryInfo {
            get {
                return ResourceManager.GetString("QueryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        internal static string Quiz {
            get {
                return ResourceManager.GetString("Quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realtime Scheduling.
        /// </summary>
        internal static string RealtimeScheduling {
            get {
                return ResourceManager.GetString("RealtimeScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        internal static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling.
        /// </summary>
        internal static string Scheduling {
            get {
                return ResourceManager.GetString("Scheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search term.
        /// </summary>
        internal static string SearchTerm {
            get {
                return ResourceManager.GetString("SearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Shortest Path to .
        /// </summary>
        internal static string ShortestPath_Info_1 {
            get {
                return ResourceManager.GetString("ShortestPath_Info_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  starting from .
        /// </summary>
        internal static string ShortestPath_Info_2 {
            get {
                return ResourceManager.GetString("ShortestPath_Info_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is available over: .
        /// </summary>
        internal static string ShortestPath_Info_3 {
            get {
                return ResourceManager.GetString("ShortestPath_Info_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortest Paths.
        /// </summary>
        internal static string ShortestPaths {
            get {
                return ResourceManager.GetString("ShortestPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show solution.
        /// </summary>
        internal static string ShowSolution {
            get {
                return ResourceManager.GetString("ShowSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side dishes.
        /// </summary>
        internal static string Sidedishes {
            get {
                return ResourceManager.GetString("Sidedishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soups.
        /// </summary>
        internal static string Soups {
            get {
                return ResourceManager.GetString("Soups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        internal static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your status at HSHL.
        /// </summary>
        internal static string StatusQuery {
            get {
                return ResourceManager.GetString("StatusQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation.
        /// </summary>
        internal static string TableLabel_CRC_Calculation {
            get {
                return ResourceManager.GetString("TableLabel_CRC_Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string TableLabel_CRC_Check {
            get {
                return ResourceManager.GetString("TableLabel_CRC_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string TableLabel_PageReplacement_Distance {
            get {
                return ResourceManager.GetString("TableLabel_PageReplacement_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointer.
        /// </summary>
        internal static string TableLabel_PageReplacement_Pointer {
            get {
                return ResourceManager.GetString("TableLabel_PageReplacement_Pointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string TableLabel_PageReplacement_Reference {
            get {
                return ResourceManager.GetString("TableLabel_PageReplacement_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot.
        /// </summary>
        internal static string TableLabel_PageReplacement_Slot {
            get {
                return ResourceManager.GetString("TableLabel_PageReplacement_Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong.
        /// </summary>
        internal static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food coloring.
        /// </summary>
        internal static string Z1 {
            get {
                return ResourceManager.GetString("Z1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains phenylalanine.
        /// </summary>
        internal static string Z10 {
            get {
                return ResourceManager.GetString("Z10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taurine.
        /// </summary>
        internal static string Z11 {
            get {
                return ResourceManager.GetString("Z11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitrite pickling salt.
        /// </summary>
        internal static string Z12 {
            get {
                return ResourceManager.GetString("Z12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caffeinated.
        /// </summary>
        internal static string Z13 {
            get {
                return ResourceManager.GetString("Z13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains quinine.
        /// </summary>
        internal static string Z14 {
            get {
                return ResourceManager.GetString("Z14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milk protein.
        /// </summary>
        internal static string Z15 {
            get {
                return ResourceManager.GetString("Z15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preservatives.
        /// </summary>
        internal static string Z2 {
            get {
                return ResourceManager.GetString("Z2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antioxidants.
        /// </summary>
        internal static string Z3 {
            get {
                return ResourceManager.GetString("Z3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flavor enhancer.
        /// </summary>
        internal static string Z4 {
            get {
                return ResourceManager.GetString("Z4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosphate.
        /// </summary>
        internal static string Z5 {
            get {
                return ResourceManager.GetString("Z5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulphureted.
        /// </summary>
        internal static string Z6 {
            get {
                return ResourceManager.GetString("Z6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waxed.
        /// </summary>
        internal static string Z7 {
            get {
                return ResourceManager.GetString("Z7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackened.
        /// </summary>
        internal static string Z8 {
            get {
                return ResourceManager.GetString("Z8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweetener(s).
        /// </summary>
        internal static string Z9 {
            get {
                return ResourceManager.GetString("Z9", resourceCulture);
            }
        }
    }
}
