name: CI
on: 
  push:
  schedule:
    - cron:  '0 1 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK 
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '7.0.x'
      - run: ls && dotnet test

